env_variables:
  FOO: "Hello from App Engine"
runtime: nodejs14
manual_scaling:
   instances: 1
resources:
   cpu: 1
   memory_gb: 0.5
   disk_size_gb: 10




#OPTIONAL

automatic_scaling:
   min_num_instances: 1
   max_num_instances: 5
   cool_down_period_sec: 180
   cpu_utilization:
      target_utilization: 0.6
