version: "3.7"

services:
  anyApp:
    build:
      context: src/${PROJECT_LANG:-python}
    image: ${DOCKER_REPO:-kontinu}/${PROJECT_LANG:-python}-expert:v3.0
    environment:
      - FOO=bar
      - NEXT_URL
    init: true

    ports:
    - 8080:8080

