version: "3.7"

services:
  anyApp:
    build:
      context: src/${PROJECT_LANG:-python}
    image: gcr.io/${GOOGLE_CLOUD_PROJECT:-kontinu}/${PROJECT_LANG:-python}-gcp:v1.0
    environment:
      - FOO=bar
      - NEXT_URL
    init: true

    ports:
    - 8080:8080

