version: "3.7"

services:
  anyApp:
    build:
      context: src/${PROJECT_LANG:-python}
      args:
        version: ${version:-1.0}
    image: ${REGISTRY:-us-east1-docker.pkg.dev}/${GOOGLE_CLOUD_PROJECT:-kontinu}/${PROJECT_LANG:-python}-gcp/app:v${version:-1.0}
    #image: gcr.io/${GOOGLE_CLOUD_PROJECT:-kontinu}/${PROJECT_LANG:-python}-gcp:v${version:-1.0}
    environment:
      - FOO=bar
      - NEXT_URL
    init: true

    ports:
    - 8080:8080

