apiVersion: apps/v1
kind: Deployment
metadata:
  name: kontinu-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kontinu-operator
  template:
    metadata:
      labels:
        name: kontinu-operator
    spec:
      serviceAccountName: kontinu-operator
      containers:
        - name: kontinu-operator
          # Replace this with the built image name
          image: kontinu/python-expert:v1.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kontinu-operator"
