apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustom-

bases:
- ../manifests

# patchesStrategicMerge:
# - patch-deployment.yaml
images:
  - name: gcr.io/kontinu/python-gcp
    newName: gcr.io/my-project/python-gcp
    newTag: v1.0
